services:
  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - ./dynamodb-data:/home/dynamodblocal/data
    command: >
      -jar DynamoDBLocal.jar
      -sharedDb
      -dbPath /home/dynamodblocal/data

  dynamodb-shell:
    image: amazon/aws-cli:latest
    container_name: dynamodb-shell
    depends_on:
      - dynamodb-local
    environment:
      AWS_ACCESS_KEY_ID: fake
      AWS_SECRET_ACCESS_KEY: fake
      AWS_DEFAULT_REGION: us-east-1
    entrypoint: ["sh", "-c"]
    command: ["sleep infinity"]
